### PR TITLE
✨ Add perturbation use-case

### PR DESCRIPTION
**Pull request by Zethson**
- Adds a perturbation use-case using McFarland 2020
- Fixes several cleanup cells and missing `hide-output` tags

### CODE REVIEW

**Comment by sunnyosun** [comment]
Could we have all features lower case, here "DepMap_ID":

Screenshot 2024-09-23 at 17 41 06

**Comment by sunnyosun** [comment]
Could you put "CRISPRi" instead of "CRISPR"? (in contrast to "CRISPRa" is overexpression)?

Could you call the 2nd type "drug" to "compound"? So it's consistent with the registry name

Screenshot 2024-09-23 at 17 41 57

**Comment by sunnyosun** [comment]
This here is still protein, could you change it to gene please?

Screenshot 2024-09-23 at 17 45 09

**Comment by sunnyosun** [comment]
I'd suggest:
```
wl.GeneticTreatment(
    system="CRISPRi",
    name="sgGPX4-1",
)
```
You can then directly use `GeneticTreatment` to validate `perturbation` column:

Screenshot 2024-09-23 at 17 46 50

**Comment by sunnyosun** [comment]
This is quite long as you are repeating the process 4 times, could we simplify with a loop?

Screenshot 2024-09-23 at 17 50 58

**Comment by sunnyosun** [comment]
Is it possible to map out the compound names manually? Relying on search here feels quite hacky:

Screenshot 2024-09-23 at 17 59 27

**Comment by Zethson** [comment]
> Is it possible to map out the compound names manually? Relying on search here feels quite hacky:
> Screenshot 2024-09-23 at 17 59 27

Required renaming a compound which got created using a synonym in the data because else `.get(name="bla")` would not find it. `search()` results in less code but `.get()` is less hacky.

**Comment by falexwolf** [comment]
Adding a few more nitpicks to this: https://66f2c423c38feb18dc1d77b4--lamin-usecases-ddcd.netlify.app/perturbation 😇 

This is a continuation of the Slack [thread](https://laminlabs.slack.com/archives/C03Q5TXF797/p1727255509225919?thread_ts=1727253591.934049&cid=C03Q5TXF797).

(2) The docs aren't an academic paper or blog and referring to authors should be avoided. Hence rather than saying "In this guide we demonstrate", we should say "This guide demonstrates".

image

**Comment by falexwolf** [comment]
This sentence would be nice to have right before you load the anndata.

image

As discussed in a dedicated [thread on Slack](https://laminlabs.slack.com/archives/C046F63LJJ2/p1723615910685469), I don't think we should put datasets into the Python package `lamin_usecases` and expect people to pip install it.

I think we should use lamindb to transfer this datasets from `lamindb-dev-datasets` instead. `lamindb-dev-datasets` stores an artifact without metadata, the test instance on CI curates it.

**Comment by falexwolf** [comment]
image

As discussed in a dedicated [thread on Slack](https://laminlabs.slack.com/archives/C046F63LJJ2/p1723615910685469), I don't think we should put datasets into the Python package lamin_usecases and expect people to pip install it.

I think we should use lamindb to transfer this datasets from lamindb-dev-datasets instead. lamindb-dev-datasets stores an artifact without metadata, the test instance on CI curates it.

**Pull request merged**
